### ISSUE TITLE
Reload API endpoint does not refresh/re-run spawnpoint count

### ISSUE THREAD

**Issue by mkllrtxn** [UnownHash/Fletchling#38]
I don't know if I am doing something wrong or skipping any step. I have some Nests that are filled with 0 spawnpoints, but I have checked in RM and Koji that in fact there are spawnpoints in there...
![Captura_de_pantalla_2024-03-13_a_las_13 05 41](https://github.com/UnownHash/Fletchling/assets/53058001/d3aa541b-5471-4563-bb7a-edf6bd70c670)

I have tried to reload fletchling, with refresh=1 and with refresh=1&spawnpoints=all and it continues counting 0 spawnpoints.

EDIT:
I had to manually remove the nest from db and import it again. Then using refresh=1&spawnpoints=all spawnpoints have been counted. It seems that this api endpoint http://localhost:9042/api/config/reload?refresh=1&spawnpoints=all doesn't rerun/refresh spawnpoint count if it has a value. It only refreshes if it is NULL.

EDIT 2:
Okey, I think I have been able to reproduce it
If a nest is activated and you force spawnpoints to 0, if you reload with spawnpoint=all, spawnpoints are populated.
If a nest is not activated and it has 0 spawnpoints, if you reload it, it wont update spawnpoints

**Comment by comstud** [comment]
I found it. It's a stupid bug. It actually can behave a bit randomly. Fix will be coming shortly.
