### ISSUE TITLE
Importer - add only-new flag

### ISSUE THREAD

**Issue by lenisko** [UnownHash/Fletchling#43]
Add a flag to quickly process areas missing in `nests` table. Useful to quickly add nests for newly added areas.

Example usage:
```
./fletchling-osm-importer -all-areas -only-new
```

That would fetch all unique `area_name` and process only unmatched areas.

**Comment by comstud** [comment]
Good idea. Should be easy

**Comment by comstud** [comment]
I'm making this '-new-areas' and it will just imply '-all-areas' such that you don't need to specify both.
