### ISSUE TITLE
Add option for koji `replace` param

### ISSUE THREAD

**Issue by kamieniarz** [UnownHash/Fletchling#51]
When I use `/api/v1/geofence/feature-collection/Nest?replace=%22-nest%22` I'm getting error:
```
INFO 2024-03-24 12:40:02 Reloading areas from koji project 'Nest'
ERRO 2024-03-24 12:40:02 Failed to load areas: invalid character '<' looking for beginning of value.
```
That's actually a big issue for me cause I can't duplicate some areas with same names (eg. new york -> New York) and that would require rethink my whole koji setup and rename lots of areas :(

To fix it I simply opened my url and saved content to a file that I used in config instead of koji. It works but it requires manual updates each time I change anything in koji :/

**Comment by comstud** [comment]
Ugh. I'm behind at looking at issues... Sorry. Will try to look at this soon.
